Repository cat2k22/Hacktobersest2023, pull requests merged in 2023-10, with the labels that each got.

#14 Develop Simple Login Page #2 Issue resolved
  Login/login.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#15 Add files via upload
  Login-page validation/index.html
  Login-page validation/script.js
  Login-page validation/style.css
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#16 Add files via upload
  countdown-timer/README.md
  countdown-timer/assets/tones/Alarm05.wav
  countdown-timer/index.html
  countdown-timer/scripts/main.js
  countdown-timer/styles/style.css
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, Hard

#17 Added Car game files
  Card-Game/css/style.min.css
  Card-Game/images/burger.png
  Card-Game/images/doughnut.png
  Card-Game/images/ice-cream-2.png
  Card-Game/images/ice-cream-3.png
  Card-Game/images/ice-cream.png
  Card-Game/images/ketchup.png
  Card-Game/images/letter-m.png
  Card-Game/images/pineapple.png
  Card-Game/images/pizza.png
  Card-Game/images/strawberry.png
  Card-Game/images/watermelon.png
  Card-Game/index.html
  Card-Game/sass/style.scss
  Card-Game/script.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
